In [6]:
import httpx
import tomli
import pandas as pd

with open('config.toml','rb') as f:
	config = tomli.load(f)

'{"help": "https://localhost:8443/api/3/action/help_show?name=datastore_search", "success": true, "result": {"include_total": true, "limit": 100, "records_format": "objects", "resource_id": "efc9d958-e438-4d29-8db1-cdee343a9092", "total_estimation_threshold": null, "records": [{"_id":1,"dms_site_id":"CVWD 17","agency":"CVWD","local_site_id":1000541},{"_id":2,"dms_site_id":"CVWD 11","agency":"CVWD","local_site_id":1002294},{"_id":3,"dms_site_id":"CVWD 12","agency":"CVWD","local_site_id":1002289},{"_id":4,"dms_site_id":"CVWD 15","agency":"CVWD","local_site_id":1000543},{"_id":5,"dms_site_id":"CVWD 16","agency":"CVWD","local_site_id":1000547},{"_id":6,"dms_site_id":"CVWD 19","agency":"CVWD","local_site_id":1000568},{"_id":7,"dms_site_id":"CVWD 24","agency":"CVWD","local_site_id":1000569},{"_id":8,"dms_site_id":"CVWD 20","agency":"CVWD","local_site_id":1000573},{"_id":9,"dms_site_id":"CVWD 21","agency":"CVWD","local_site_id":1000570},{"_id":10,"dms_site_id":"CVWD 26","agency":"CVWD","local_site_id":1000540},{"_id":11,"dms_site_id":"CVWD 33","agency":"CVWD","local_site_id":1000594},{"_id":12,"dms_site_id":"CVWD 34","agency":"CVWD","local_site_id":1203746},{"_id":13,"dms_site_id":"SAWC 02","agency":"SAWC","local_site_id":1000562},{"_id":14,"dms_site_id":"SAWC 19","agency":"SAWC","local_site_id":1000559},{"_id":15,"dms_site_id":"SAWC 31","agency":"SAWC","local_site_id":1000580},{"_id":16,"dms_site_id":"SAWC 32","agency":"SAWC","local_site_id":1006968},{"_id":17,"dms_site_id":"Upland 07A","agency":"City of Upland","local_site_id":null},{"_id":18,"dms_site_id":"Hellman Ave","agency":"CVWD","local_site_id":1000593},{"_id":19,"dms_site_id":"SAWC 33","agency":"SAWC","local_site_id":1207955},{"_id":20,"dms_site_id":"CVWD 27","agency":"CVWD","local_site_id":1000525},{"_id":21,"dms_site_id":"VCT-2","agency":"Inland Empire Utilities Agency","local_site_id":1223006},{"_id":22,"dms_site_id":"Upland 09","agency":"City of Upland","local_site_id":1002313},{"_id":23,"dms_site_id":"Upland 05","agency":"City of Upland","local_site_id":null},{"_id":24,"dms_site_id":"CVWD 30","agency":"CVWD","local_site_id":null},{"_id":25,"dms_site_id":"CVWD 05","agency":"CVWD","local_site_id":null},{"_id":26,"dms_site_id":"CVWD 04","agency":"CVWD","local_site_id":null},{"_id":27,"dms_site_id":"CVWD 38","agency":"CVWD","local_site_id":null},{"_id":28,"dms_site_id":"CVWD 14","agency":"CVWD","local_site_id":null},{"_id":29,"dms_site_id":"CVWD 18","agency":"CVWD","local_site_id":null},{"_id":30,"dms_site_id":"SAWC 16","agency":"SAWC","local_site_id":null},{"_id":31,"dms_site_id":"WVWD 54","agency":"WVWD","local_site_id":null},{"_id":32,"dms_site_id":"OMUC 09","agency":"OMUC","local_site_id":null},{"_id":33,"dms_site_id":"CVWD 08","agency":"CVWD","local_site_id":1002288},{"_id":34,"dms_site_id":"CVWD 10","agency":"CVWD","local_site_id":1002287},{"_id":35,"dms_site_id":"CVWD 22","agency":"CVWD","local_site_id":1200714},{"_id":36,"dms_site_id":"SAWC 03","agency":"SAWC","local_site_id":1000563},{"_id":37,"dms_site_id":"SAWC 22","agency":"SAWC","local_site_id":1002298},{"_id":38,"dms_site_id":"CVWD 31","agency":"CVWD","local_site_id":1000591},{"_id":39,"dms_site_id":"OMUC 46","agency":"OMUC","local_site_id":null},{"_id":40,"dms_site_id":"8th-1-1","agency":"Inland Empire Utilities Agency","local_site_id":null},{"_id":41,"dms_site_id":"8th-1-2","agency":"Inland Empire Utilities Agency","local_site_id":null},{"_id":42,"dms_site_id":"8th-2-1","agency":"Inland Empire Utilities Agency","local_site_id":null},{"_id":43,"dms_site_id":"VCT-1-1","agency":"Inland Empire Utilities Agency","local_site_id":null},{"_id":44,"dms_site_id":"SS-1","agency":"Inland Empire Utilities Agency","local_site_id":null},{"_id":45,"dms_site_id":"Upland Foothills 03","agency":"City of Upland","local_site_id":null},{"_id":46,"dms_site_id":"SAWC 24","agency":"SAWC","local_site_id":1000576},{"_id":47,"dms_site_id":"SAWC 12","agency":"SAWC","local_site_id":null},{"_id":48,"dms_site_id":"CVWD 01","agency":"CVWD","local_site_id":null},{"_id":49,"dms_site_id":"OMUC 41","agency":"OMUC","local_site_id":null},{"_id":50,"dms_site_id":"CVWD 23","agency":"CVWD","local_site_id":1000590},{"_id":51,"dms_site_id":"CVWD 13","agency":"CVWD","local_site_id":1000539},{"_id":52,"dms_site_id":"OMUC 52","agency":"OMUC","local_site_id":null},{"_id":53,"dms_site_id":"8th-2-2","agency":"Inland Empire Utilities Agency","local_site_id":null},{"_id":54,"dms_site_id":"SS-2","agency":"Inland Empire Utilities Agency","local_site_id":null},{"_id":55,"dms_site_id":"SAWC 15","agency":"SAWC","local_site_id":1000555},{"_id":56,"dms_site_id":"Upland 15","agency":"City of Upland","local_site_id":1000554},{"_id":57,"dms_site_id":"OMUC 47","agency":"OMUC","local_site_id":null},{"_id":58,"dms_site_id":"Upland 20","agency":"City of Upland","local_site_id":null}], "fields": [{"id": "_id", "type": "int"}, {"id": "dms_site_id", "type": "text"}, {"id": "agency", "type": "text"}, {"id": "local_site_id", "type": "numeric"}], "_links": {"start": "/api/3/action/datastore_search?resource_id=efc9d958-e438-4d29-8db1-cdee343a9092", "next": "/api/3/action/datastore_search?resource_id=efc9d958-e438-4d29-8db1-cdee343a9092&offset=100"}, "total": 58, "total_was_estimated": false}}'

In [52]:
table_id = "efc9d958-e438-4d29-8db1-cdee343a9092"
base_url = 'https://localhost:8443/api/3/action'
url = base_url + '/datastore_search'

C = httpx.Client(
	headers={'Authorization': config['CKAN']['token']},
	verify=False)

r = C.get(
	url,
	params={'resource_id':table_id},
	)
r.text

'{"help": "https://localhost:8443/api/3/action/help_show?name=datastore_search", "success": true, "result": {"include_total": true, "limit": 100, "records_format": "objects", "resource_id": "efc9d958-e438-4d29-8db1-cdee343a9092", "total_estimation_threshold": null, "records": [{"_id":1,"dms_site_id":"CVWD 17","agency":"CVWD","local_site_id":1000541},{"_id":2,"dms_site_id":"CVWD 11","agency":"CVWD","local_site_id":1002294},{"_id":3,"dms_site_id":"CVWD 12","agency":"CVWD","local_site_id":1002289},{"_id":4,"dms_site_id":"CVWD 15","agency":"CVWD","local_site_id":1000543},{"_id":5,"dms_site_id":"CVWD 16","agency":"CVWD","local_site_id":1000547},{"_id":6,"dms_site_id":"CVWD 19","agency":"CVWD","local_site_id":1000568},{"_id":7,"dms_site_id":"CVWD 24","agency":"CVWD","local_site_id":1000569},{"_id":8,"dms_site_id":"CVWD 20","agency":"CVWD","local_site_id":1000573},{"_id":9,"dms_site_id":"CVWD 21","agency":"CVWD","local_site_id":1000570},{"_id":10,"dms_site_id":"CVWD 26","agency":"CVWD","local_site_id":1000540},{"_id":11,"dms_site_id":"CVWD 33","agency":"CVWD","local_site_id":1000594},{"_id":12,"dms_site_id":"CVWD 34","agency":"CVWD","local_site_id":1203746},{"_id":13,"dms_site_id":"SAWC 02","agency":"SAWC","local_site_id":1000562},{"_id":14,"dms_site_id":"SAWC 19","agency":"SAWC","local_site_id":1000559},{"_id":15,"dms_site_id":"SAWC 31","agency":"SAWC","local_site_id":1000580},{"_id":16,"dms_site_id":"SAWC 32","agency":"SAWC","local_site_id":1006968},{"_id":17,"dms_site_id":"Upland 07A","agency":"City of Upland","local_site_id":null},{"_id":18,"dms_site_id":"Hellman Ave","agency":"CVWD","local_site_id":1000593},{"_id":19,"dms_site_id":"SAWC 33","agency":"SAWC","local_site_id":1207955},{"_id":20,"dms_site_id":"CVWD 27","agency":"CVWD","local_site_id":1000525},{"_id":21,"dms_site_id":"VCT-2","agency":"Inland Empire Utilities Agency","local_site_id":1223006},{"_id":22,"dms_site_id":"Upland 09","agency":"City of Upland","local_site_id":1002313},{"_id":23,"dms_site_id":"Upland 05","agency":"City of Upland","local_site_id":null},{"_id":24,"dms_site_id":"CVWD 30","agency":"CVWD","local_site_id":null},{"_id":25,"dms_site_id":"CVWD 05","agency":"CVWD","local_site_id":null},{"_id":26,"dms_site_id":"CVWD 04","agency":"CVWD","local_site_id":null},{"_id":27,"dms_site_id":"CVWD 38","agency":"CVWD","local_site_id":null},{"_id":28,"dms_site_id":"CVWD 14","agency":"CVWD","local_site_id":null},{"_id":29,"dms_site_id":"CVWD 18","agency":"CVWD","local_site_id":null},{"_id":30,"dms_site_id":"SAWC 16","agency":"SAWC","local_site_id":null},{"_id":31,"dms_site_id":"WVWD 54","agency":"WVWD","local_site_id":null},{"_id":32,"dms_site_id":"OMUC 09","agency":"OMUC","local_site_id":null},{"_id":33,"dms_site_id":"CVWD 08","agency":"CVWD","local_site_id":1002288},{"_id":34,"dms_site_id":"CVWD 10","agency":"CVWD","local_site_id":1002287},{"_id":35,"dms_site_id":"CVWD 22","agency":"CVWD","local_site_id":1200714},{"_id":36,"dms_site_id":"SAWC 03","agency":"SAWC","local_site_id":1000563},{"_id":37,"dms_site_id":"SAWC 22","agency":"SAWC","local_site_id":1002298},{"_id":38,"dms_site_id":"CVWD 31","agency":"CVWD","local_site_id":1000591},{"_id":39,"dms_site_id":"OMUC 46","agency":"OMUC","local_site_id":null},{"_id":40,"dms_site_id":"8th-1-1","agency":"Inland Empire Utilities Agency","local_site_id":null},{"_id":41,"dms_site_id":"8th-1-2","agency":"Inland Empire Utilities Agency","local_site_id":null},{"_id":42,"dms_site_id":"8th-2-1","agency":"Inland Empire Utilities Agency","local_site_id":null},{"_id":43,"dms_site_id":"VCT-1-1","agency":"Inland Empire Utilities Agency","local_site_id":null},{"_id":44,"dms_site_id":"SS-1","agency":"Inland Empire Utilities Agency","local_site_id":null},{"_id":45,"dms_site_id":"Upland Foothills 03","agency":"City of Upland","local_site_id":null},{"_id":46,"dms_site_id":"SAWC 24","agency":"SAWC","local_site_id":1000576},{"_id":47,"dms_site_id":"SAWC 12","agency":"SAWC","local_site_id":null},{"_id":48,"dms_site_id":"CVWD 01","agency":"CVWD","local_site_id":null},{"_id":49,"dms_site_id":"OMUC 41","agency":"OMUC","local_site_id":null},{"_id":50,"dms_site_id":"CVWD 23","agency":"CVWD","local_site_id":1000590},{"_id":51,"dms_site_id":"CVWD 13","agency":"CVWD","local_site_id":1000539},{"_id":52,"dms_site_id":"OMUC 52","agency":"OMUC","local_site_id":null},{"_id":53,"dms_site_id":"8th-2-2","agency":"Inland Empire Utilities Agency","local_site_id":null},{"_id":54,"dms_site_id":"SS-2","agency":"Inland Empire Utilities Agency","local_site_id":null},{"_id":55,"dms_site_id":"SAWC 15","agency":"SAWC","local_site_id":1000555},{"_id":56,"dms_site_id":"Upland 15","agency":"City of Upland","local_site_id":1000554},{"_id":57,"dms_site_id":"OMUC 47","agency":"OMUC","local_site_id":null},{"_id":58,"dms_site_id":"Upland 20","agency":"City of Upland","local_site_id":null}], "fields": [{"id": "_id", "type": "int"}, {"id": "dms_site_id", "type": "text"}, {"id": "agency", "type": "text"}, {"id": "local_site_id", "type": "numeric"}], "_links": {"start": "/api/3/action/datastore_search?resource_id=efc9d958-e438-4d29-8db1-cdee343a9092", "next": "/api/3/action/datastore_search?resource_id=efc9d958-e438-4d29-8db1-cdee343a9092&offset=100"}, "total": 58, "total_was_estimated": false}}'

In [53]:
df = pd.DataFrame(r.json()['result']['records'])
print(df.shape)
df.head()

(58, 4)

   _id dms_site_id agency  local_site_id
0    1     CVWD 17   CVWD      1000541.0
1    2     CVWD 11   CVWD      1002294.0
2    3     CVWD 12   CVWD      1002289.0
3    4     CVWD 15   CVWD      1000543.0
4    5     CVWD 16   CVWD      1000547.0

In [50]:
url = base_url + '/group_list'
r = C.get(
	url,
	params={'resource_id':table_id},
	)
df = pd.DataFrame(r.json()['result']).rename(columns={0:'group'})
df.head(2)
# r.json()

             group
0  cucamonga_basin

In [61]:
url = base_url + '/datastore_upsert'

wells = [{
	# 'dms_site_id':'test',
	# 'agency':'text',
	# 'local_site_id':2000547.0
	}]

r = C.post(
	url,
	data={
		'resource_id':table_id,
		'records':wells,
		'method':'insert',
		'force':True,
	}
	)
print(r.url)
print(r.reason_phrase)

r.json()
# r.url

https://localhost:8443/api/3/action/datastore_upsert
CONFLICT

{'help': 'https://localhost:8443/api/3/action/help_show?name=datastore_upsert',
 'error': {'records': ['row "0" is not a json object'],
  '__type': 'Validation Error'},
 'success': False}

In [60]:
txt = httpx.get("https://localhost:8443/api/3/action/help_show?name=datastore_upsert",verify=False).json()['result']
print(txt)

Updates or inserts into a table in the DataStore

    The datastore_upsert API action allows you to add or edit records to
    an existing DataStore resource. In order for the *upsert* and *update*
    methods to work, a unique key has to be defined via the datastore_create
    action. The available methods are:

    *upsert*
        Update if record with same key already exists, otherwise insert.
        Requires unique key or _id field.
    *insert*
        Insert only. This method is faster that upsert, but will fail if any
        inserted record matches an existing one. Does *not* require a unique
        key.
    *update*
        Update only. An exception will occur if the key that should be updated
        does not exist. Requires unique key or _id field.


    :param resource_id: resource id that the data is going to be stored under.
    :type resource_id: string
    :param force: set to True to edit a read-only resource
    :type force: bool (optional, default: False)
    :param records: the data, eg: [{"dob": "2005", "some_stuff": ["a","b"]}]
                    (optional)
    :type records: list of dictionaries
    :param method: the method to use to put the data into the datastore.
                   Possible options are: upsert, insert, update
                   (optional, default: upsert)
    :type method: string
    :param calculate_record_count: updates the stored count of records, used to
        optimize datastore_search in combination with the
        `total_estimation_threshold` parameter. If doing a series of requests
        to change a resource, you only need to set this to True on the last
        request.
    :type calculate_record_count: bool (optional, default: False)
    :param dry_run: set to True to abort transaction instead of committing,
                    e.g. to check for validation or type errors.
    :type dry_run: bool (optional, default: False)

    **Results:**

    :returns: The modified data object.
    :rtype: dictionary